export const DICTIONARY = [
  {
    Word: 'aac',
    Definition:
      'Augmentative and alternative communication describes a communication method used by an individual who does not use verbal speech. AAC systems are designed to help people express their thoughts, needs and ideas.',
    Link: 'https://undivided.io/resources/314',
  },
  {
    Word: 'aba',
    Definition: 'Applied Behavioral Analysis',
    Link: 'https://undivided.io/resources/603',
  },
  {
    Word: 'acse',
    Definition: 'Advisory Commission on Special Education',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'ada',
    Definition: 'American Disabilities Act',
    Link: 'https://community.undivided.io/news/12058',
  },
  {
    Word: 'adhd',
    Definition: 'Attention Deficit Hyperactivity Disorder',
    Link: 'https://undivided.io/resources/200',
  },
  {
    Word: 'advocacy',
    Definition:
      "Parents of children with disabilities advocate for their child whether they're at an IEP, the doctor's office, or the local playground. Many moms and dads extend their advocacy beyond their own family and become a powerful voice for the community.",
    Link: 'https://undivided.io/',
  },
  {
    Word: 'advocate',
    Definition:
      'Parents of children with disabilities frequently have to advocate for their child. Some parents also hire a professional advocate to accompany them to an IEP meeting.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'asd',
    Definition: 'Autism Spectrum Disorder',
    Link: 'https://undivided.io/resources/204',
  },
  {
    Word: 'assess',
    Definition:
      "The first step to providing any service through an IEP or IPP is to assess a child's needs. The assessment(s) can establish eligibility, areas of need, and the appropriate frequency of services.",
    Link: 'https://undivided.io/resources/115',
  },
  {
    Word: 'assessment',
    Definition:
      "The first step to providing any service through an IEP or IPP is to assess a child's needs. The assessment(s) can establish eligibility, areas of need, and the appropriate frequency of services.",
    Link: 'https://undivided.io/resources/115',
  },
  {
    Word: 'assistive',
    Definition:
      'Assistive technology (AT) is any equipment, program, or system that is used to increase, maintain, or improve the functional capabilities of people with disabilities. AT can be both high-tech, such as an iPad, and low-tech, such as a communication board.',
    Link: 'https://undivided.io/resources/690',
  },
  {
    Word: 'basc',
    Definition:
      'Behavior Assessment System for Children is a test often used for an Functional Behavioral Assessment',
    Link: 'https://undivided.io/resources/308',
  },
  {
    Word: 'baseline',
    Definition:
      'In an IEP, each goal requires a baseline statement of the present levels of performance.',
    Link: 'https://undivided.io/resources/125',
  },
  {
    Word: 'bcaba',
    Definition: 'Board Certified Assistant Behavior Analyst',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'bcba',
    Definition: 'Board Certified Behavior Analyst',
    Link: 'https://undivided.io/resources/322',
  },
  {
    Word: 'behavior',
    Definition:
      '... is communication. Many children with disabilities have issues with behavior that can impede their learning, their ability to make friends, and drive their parents to occasionally go outside and scream into the rosemary bush.',
    Link: 'https://undivided.io/resources/310',
  },
  {
    Word: 'belonging',
    Definition:
      'An affinity or sense of being a part of a place or group of people. Not being other. (Also known as inclusion.)',
    Link: 'https://undivided.io/resources/298',
  },
  {
    Word: 'binder',
    Definition:
      "You should keep and organize all the paperwork generated by your child's IEP and other services in a binder. Undivided has created a digital binder that can be shared with any teacher or provider.",
    Link: 'https://undivided.io/resources/119',
  },
  {
    Word: 'bip',
    Definition: 'Behavior Intervention Plan',
    Link: 'https://undivided.io/resources/308',
  },
  {
    Word: 'caa',
    Definition: 'California Alternate Assessment',
    Link: 'https://undivided.io/resources/536',
  },
  {
    Word: 'calable',
    Definition:
      'An individual is automatically eligible for CalABLE if they have a disability that occurred before age 26 and they receive benefits under Supplemental Security Income (SSI) or Social Security Disability Insurance (SSDI).',
    Link: 'https://undivided.io/resources/300',
  },
  {
    Word: 'caaspp',
    Definition: 'California Assessment of Student Performance and Progress',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'ccs',
    Definition: "California Children's Services",
    Link: 'https://undivided.io/resources/300',
  },
  {
    Word: 'compliance',
    Definition:
      '... is acting on command or according to the rules of law. A school district can be out of compliance. Compliance training has been criticized for making children with disabilities vulnerable to abuse.',
    Link: 'https://undivided.io/resources/893',
  },
  {
    Word: 'consent',
    Definition:
      'Permission for something to happen or agreement to do something is essential to autonomy. Often children and adults with disabilities are not asked for their consent due to our failure to presume competence. Teaching a child consent can happen naturally — for example, when they get their blood drawn. Consent is an important first step in protecting children with disabilities from abuse.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'curriculum',
    Definition:
      'Many states including California have adopted the Common Core State Standards as the framework for a core curriculum in K–12 schools. Core Content Connectors and Essential Understandings can help bridge the gap for both children with disabilities and their neurotypical peers.',
    Link: 'https://undivided.io/resources/311',
  },
  {
    Word: 'dds',
    Definition: 'Department of Developmental Services',
    Link: 'https://www.dds.ca.gov/',
  },
  {
    Word: 'deafness',
    Definition:
      'Under IDEA, a child who is deaf or hard of hearing may be eligible for special education (and thus an IEP) if they are unable to hear most or all sounds even with a hearing aid.',
    Link: 'https://undivided.io/resources/129',
  },
  {
    Word: 'deeming',
    Definition:
      'Several government benefit programs, including IHSS, require that your child be enrolled in Medi-Cal before you can access services. Families whose income exceeds Medi-Cal’s qualifying threshold may be eligible for the Home and Community-Based Services for the Developmentally Disabled Waiver, otherwise known as the institutional deeming waiver.',
    Link: 'https://undivided.io/resources/169',
  },
  {
    Word: 'designated',
    Definition:
      'Designated Instruction and Services (DIS) are otherwise known in special education as related services that are necessary for a student to benefit from his/her special education program.',
    Link: 'https://undivided.io/resources/663',
  },
  {
    Word: 'dhh',
    Definition: 'Deaf and Hard of Hearing',
    Link: 'https://undivided.io/resources/124',
  },
  {
    Word: 'diagnosis',
    Definition:
      'The identification of a disability and its impact/nature. Note that a medical diagnosis might have different criteria from the eligibility category for an IEP.',
    Link: 'https://undivided.io/resources/129',
  },
  {
    Word: 'diploma',
    Definition:
      'To receive a high school diploma, there are basic state requirements. Your local district may also have its own (and often more stringent) requirements. Many children with extensive support needs may instead work toward a certificate of completion.',
    Link: 'https://community.undivided.io/news/162466',
  },
  {
    Word: 'disability',
    Definition:
      'A disability is any condition of the body or mind that makes it more difficult for the person with the condition to participate in certain life activities (activity limitation) and interact with the world around them (participation restrictions). Talking with your kid about disability is an important part of helping them learn about themselves and how to ask for what they need.',
    Link: 'https://undivided.io/resources/151',
  },
  {
    Word: 'dispute',
    Definition:
      "If you disagree with your IEP's narrative, the first thing you should do is email your case manager and ask if they can change it. The next step may be alternative dispute resolution, or ADR, which is a free voluntary service intended as a first stop before mediation and due process.",
    Link: 'https://undivided.io/resources/299',
  },
  {
    Word: 'dor',
    Definition: 'Department of Rehabilitation',
    Link: 'https://undivided.io/resources/476',
  },
  {
    Word: 'education',
    Definition:
      'What every child with a disability has a legal right to under IDEA: a free, public and appropriate education.',
    Link: 'https://undivided.io/resources/116',
  },
  {
    Word: 'erics',
    Definition:
      'Educationally Related Intensive Counseling Services is a related service.',
    Link: 'https://undivided.io/resources/663',
  },
  {
    Word: 'esy',
    Definition: 'Extended School Year',
    Link: 'https://undivided.io/resources/205',
  },
  {
    Word: 'evaluation',
    Definition:
      "The first step to providing any service through an IEP or IPP is to assess a child's needs. The assessment(s) can establish eligibility, areas of need, and the appropriate frequency of services.",
    Link: 'https://undivided.io/resources/115',
  },
  {
    Word: 'fape',
    Definition: 'Free, Appropriate Public Education',
    Link: 'https://undivided.io/resources/873',
  },
  {
    Word: 'fba',
    Definition: 'Functional Behavioral Assessment',
    Link: 'https://undivided.io/resources/308',
  },
  {
    Word: 'fec',
    Definition: 'Family Empowerment Center',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'feeding',
    Definition:
      'While many kids go through a phase where they’re very picky about what they’ll eat, some kids may need feeding therapy to get the nutrition (and sometimes sensory and motor support) they need to grow.',
    Link: 'https://undivided.io/resources/172',
  },
  {
    Word: 'ferpa',
    Definition:
      'The Family Educational Rights and Privacy Act is a federal law that protects the privacy of student education records.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'fluency',
    Definition:
      'Fluency, which refers to rate, pronunciation, and accuracy, is an important component of both speech therapy and learning to read.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'frc',
    Definition: 'Family Resource Center',
    Link: 'https://undivided.io/resources/263',
  },
  {
    Word: 'frequency',
    Definition:
      'In an IEP document, services must be listed with a specific frequency, such as twice weekly, or 30 x yearly. It is important to check how the frequency is written before signing your IEP.',
    Link: 'https://undivided.io/resources/299',
  },
  {
    Word: 'functional',
    Definition:
      'Functional goals in an IEP focus on developing real-world life skills as opposed to academic skills.',
    Link: 'https://undivided.io/resources/195',
  },

  {
    Word: 'hearing',
    Definition:
      'Hearing is the awareness of sound and the ability to assign meaning to that sound. Deafness and hearing loss can have a profound effect on our development, speech and language, and comprehension if not adequately supported.',
    Link: 'https://undivided.io/resources/210',
  },
  {
    Word: 'hipaa',
    Definition:
      'Health Insurance Portability and Accountability Act from 1996 sets standards for keeping medical records private.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'hoh',
    Definition: 'Hard of Hearing',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'idea',
    Definition: 'Individuals with Disabilities Education Act',
    Link: 'https://community.undivided.io/news/26661',
  },
  {
    Word: 'iee',
    Definition: 'Independent Educational Evaluation',
    Link: 'https://undivided.io/resources/115',
  },
  {
    Word: 'ifsp',
    Definition: 'Individualized Family Service Plan',
    Link: 'https://undivided.io/resources/193',
  },
  {
    Word: 'ihss',
    Definition: 'In-Home Supportive Services',
    Link: 'https://undivided.io/resources/854',
  },
  {
    Word: 'inclusion',
    Definition:
      '... is any process of support intended to overcome exclusion. Inclusion is a policy or set of practices put into place to provide equal access to opportunities and resources for people who might otherwise be excluded or marginalized, such as those who have physical or mental disabilities and members of other minority groups. The goal is belonging.',
    Link: 'https://undivided.io/resources/298',
  },
  {
    Word: 'inclusive',
    Definition:
      'Inclusive practices aim to overcome the barriers to inclusion and belonging.  A practice cannot be inclusive if it excludes a particular group.',
    Link: 'https://undivided.io/resources/298',
  },
  {
    Word: 'individual',
    Definition:
      ' Services for children and adults with disabilities need to be individualized according to the needs of the person with a disability.',
    Link: 'https://undivided.io/resources/323',
  },
  {
    Word: 'ipp',
    Definition: 'Individualized Program Plan',
    Link: 'https://undivided.io/resources/324',
  },
  {
    Word: 'learning',
    Definition:
      'Learning is something that every child, every person can do. Universal Design for Learning promotes successful learning for all students while reducing the barriers they may face due to diverse learning styles, abilities, and interests.',
    Link: 'https://undivided.io/resources/78',
  },
  {
    Word: 'lre',
    Definition: 'Least Restrictive Environment',
    Link: 'https://undivided.io/resources/124',
  },
  {
    Word: 'meaningful',
    Definition:
      'Inclusion in a physical space is not on its own sufficient — we have to change the environment to make learning a meaningful experience for each child.',
    Link: 'https://undivided.io/resources/298',
  },
  {
    Word: 'measurable',
    Definition:
      '... means capable of objective measurement, as in an IEP goal.',
    Link: 'https://undivided.io/resources/125',
  },
  {
    Word: 'mediation',
    Definition:
      "IDEA sets out a procedure when parents disagree with their child's IEP team. Mediation plays a key role, either through informal mediation",
    Link: 'https://undivided.io/',
  },
  {
    Word: 'medical',
    Definition:
      "Medi-Cal is California's Medicaid program, which provides primary or secondary health care coverage to eligible children with disabilities. As secondary coverage, Medi-Cal can help fund copays and other medical needs, such as some medical supplies (like diapers and feeding-tube formula) and durable medical equipment.",
    Link: 'https://undivided.io/resources/238',
  },
  {
    Word: 'meeting',
    Definition:
      'So many meetings! Your school must convene an IEP meeting annually to review the present levels of achievement, eligibility, goals, services, and placement. You can call an IEP at any time — in writing — and the school must meet within 30 days. An IPP meeting with your Regional Center coordinator must be held every 3 years, unless your child has an HCBS-DD Waiver, in which case you must meet annually. (You can also request an IPP meeting at any time.)',
    Link: 'https://undivided.io/resources/323',
  },
  {
    Word: 'modify',
    Definition:
      'Generally speaking, a modification to general education curriculum changes what a child learns, while an accommodation changes how a child learns or how they demonstrate what they have learned.',
    Link: 'https://undivided.io/resources/332',
  },
  {
    Word: 'npa',
    Definition: 'Non Public Agency',
    Link: 'https://undivided.io/resources/189',
  },
  {
    Word: 'nps',
    Definition: 'Non Public School',
    Link: 'https://undivided.io/resources/124',
  },
  {
    Word: 'ocr',
    Definition: 'Office of Civil Rights',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'ohi',
    Definition: 'Other Health Impairment',
    Link: 'https://undivided.io/resources/129',
  },
  {
    Word: 'outcomes',
    Definition:
      'Educationalists measure achievement using a variety of metrics related to outcomes such as math and ELA scores, graduation, employment, and postsecondary education. In special education, these outcomes are typically far lower, creating an achievement gap.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'pbis',
    Definition: 'Positive Behavioral Interventions and Supports',
    Link: 'https://undivided.io/resources/310',
  },
  {
    Word: 'pcp',
    Definition: 'Person Centered Plan',
    Link: 'https://undivided.io/resources/244',
  },
  {
    Word: 'physical',
    Definition:
      'Physical therapy (PT), also known as physiotherapy, is provided by physical therapists to promote, maintain, or restore health through physical examination, diagnosis, prognosis, patient education, physical intervention, and rehabilitation.',
    Link: 'https://undivided.io/resources/462',
  },
  {
    Word: 'placement',
    Definition:
      "Every annual IEP must consider a student's placement in terms of the educational setting within which they will receive specialized instruction and services. The law favors the classroom in which the child would be learning if they were not disabled. Note that placement is not the same as location.",
    Link: 'https://undivided.io/resources/124',
  },
  {
    Word: 'plop',
    Definition: 'Present Levels of Performance',
    Link: 'https://undivided.io/resources/128',
  },
  {
    Word: 'positive',
    Definition:
      'Positive parenting focuses on behavior intervention that “catches the child being good” and rewards the positive while paying little attention to negative behaviors. Mutual respect is an important component in positive parenting philosophy. Positive Behavioral Interventions and Supports is a related approach to school discipline and behavior management.',
    Link: 'https://undivided.io/resources/310',
  },
  {
    Word: 'procedural',
    Definition:
      'Compliance complaints are often procedural in nature rather than concerning the substance of the IEP.',
    Link: 'https://undivided.io/resources/134',
  },
  {
    Word: 'progress',
    Definition:
      "Your child's progress on their IEP goals should be measured and reported periodically; usually, this occurs each time the school provides a report card.",
    Link: 'https://undivided.io/resources/130',
  },
  {
    Word: 'provider',
    Definition:
      'From medical specialists to therapists to the many parents who work as IHSS parent providers, “provider” is a big word in our world!',
    Link: 'https://undivided.io/resources/854',
  },
  {
    Word: 'pti',
    Definition: 'Parent Training Information',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'pwn',
    Definition: 'Prior Written Notice',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'regional',
    Definition:
      'Regional Centers are a statewide network of local agencies that serve children and adults with developmental disabilities in California.',
    Link: 'https://undivided.io/resources/237',
  },
  {
    Word: 'resolution',
    Definition:
      'The first step after filing a due process complaint is to have a resolution meeting with the district to find a way to resolve the disagreement without a hearing.',
    Link: 'https://undivided.io/resources/176',
  },
  {
    Word: 'resource',
    Definition:
      'Under the California Master Plan for Special Education in 1980, resource specialists were defined as special education teachers who could provide itinerant or center-based support for kids receiving special education services in a general education setting. Children receiving early intervention services can find support at their local Family Resource Center.',
    Link: 'https://eric.ed.gov/?id=ED222026',
  },
  {
    Word: 'respite',
    Definition:
      'Regional Center offers in-home respite care services to eligible parents to help provide breaks and support in the care and supervision of their child.',
    Link: 'https://undivided.io/resources/146',
  },
  {
    Word: 'safeguard',
    Definition:
      'At every IEP, the school must give you a Notice of Procedural Safeguards (even if you only ever use it as a coffee or wine coaster).',
    Link: 'https://undivided.io/resources/134',
  },
  {
    Word: 'sai',
    Definition: 'Specialized Academic Instruction',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'scdd',
    Definition: 'State Council on Developmental Disabilities',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'screening',
    Definition:
      'A screening test evaluates a student for a condition separate from other risk factors. In the case of dyslexia, screening all first graders would allow for early diagnosis and reach children with support before they fail.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'sdc',
    Definition: 'Special Day Class',
    Link: 'https://undivided.io/resources/124',
  },
  {
    Word: 'sdp',
    Definition: 'Special Day Class',
    Link: 'https://undivided.io/resources/124',
  },
  {
    Word: 'selpa',
    Definition:
      'Special Education Local Plan Area. Can be a single district, county, or sub-county group of districts pooling resources to provide special education',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'service',
    Definition:
      'Related services can be provided through an IEP or IPP as support, specialized instruction, or therapy, or through private insurance or other funding.',
    Link: 'https://undivided.io/resources/189',
  },
  {
    Word: 'sibling',
    Definition:
      'Siblings of children with disabilities can often feel overlooked or left out. From talking with your kids about disability to enrolling them in a Sibshop, there are a variety of ways to make sure everyone in the family feels supported.',
    Link: 'https://undivided.io/resources/161',
  },
  {
    Word: 'sld',
    Definition: 'Speech and Language Disorder',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'slp',
    Definition: 'Speech Language Pathologist',
    Link: 'https://undivided.io/resources/854',
  },
  {
    Word: 'slpa',
    Definition: 'Speech and Language Pathologist Assistant',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'smart',
    Definition:
      'IEP goals should be Specific, Measurable, Achievable, Relevant, and Time-Bound.',
    Link: 'https://undivided.io/resources/125',
  },
  {
    Word: 'specialist',
    Definition:
      'a person highly skilled in a specific field, such as a neuropsychologist. An IEP team must include a person qualified to explain the assessments presented (such as an IEE).',
    Link: 'https://undivided.io/resources/271',
  },
  {
    Word: 'spectrum',
    Definition:
      'Many adults with autism are not fans of the using the word “spectrum” to describe the ways in which they function in the broader world. As self-advocate C.L. Lynch puts it, people with autism have a variety of challenges and skill sets, not a bunch of shared traits that only differ in levels of severity — in other words, “red isn’t ‘more spectrum’ than green or blue.” ',
    Link: 'https://undivided.io/resources/204',
  },
  {
    Word: 'sped',
    Definition: 'A common abbreviation for Special Education.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'ssi',
    Definition: 'Supplemental Security Income',
    Link: 'https://undivided.io/resources/300',
  },
  {
    Word: 'stimming',
    Definition:
      'Stimming is shorthand for repetitive, self-stimulatory behaviors. While stimming is commonly associated with autism, it can also occur in typically developing kids, kids with ADHD, and kids with other diagnoses',
    Link: 'https://undivided.io/resources/886',
  },
  {
    Word: 'strength',
    Definition:
      "Strength-based planning focuses on using a child's strengths as a way into learning, and is both a motivator (especially for IEP teams) and a plan for building on competence rather than focusing on challenges.",
    Link: 'https://undivided.io/resources/122',
  },
  {
    Word: 'success',
    Definition:
      'Celebrating small successes is a core component of a strength-based, positive approach to education and child development.',
    Link: 'https://undivided.io/resources/175',
  },
  {
    Word: 'support',
    Definition:
      'Providing supports in the form of accommodations, adaptations, or services makes access and inclusion possible.',
    Link: 'https://undivided.io/resources/298',
  },
  {
    Word: 'teacher',
    Definition:
      'In the past, teachers were only able to earn their credentials in general education, special education (mild to moderate or resource), or special education (moderate to severe). Recent reforms renamed special education categories as “extensive support needs,” and many universities now offer a dual credential in general education and special education.',
    Link: 'https://undivided.io/resources/721',
  },
  {
    Word: 'technology',
    Definition:
      'Assistive technology (AT) is any equipment, program, or system that is used to increase, maintain, or improve the functional capabilities of people with disabilities.',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'therapist',
    Definition:
      'A professional trained to provide treatment and rehabilitation. Children with disabilities receive a large variety of therapeutic services, most commonly speech therapy, occupational therapy, behavior intervention therapy, physical therapy, and family therapy.',
    Link: 'https://undivided.io/resources/276',
  },
  {
    Word: 'therapy',
    Definition:
      '... is treatment for a particular health or developmental challenge. Children with disabilities receive a variety of early intervention and therapeutic services, most commonly speech therapy, occupational therapy, behavior intervention therapy, physical therapy, and family therapy.',
    Link: 'https://undivided.io/resources/276',
  },
  {
    Word: 'timeline',
    Definition:
      'There are very specific timelines involved in the IEP process. For example, in California, a school has 15 school days to hold an IEP meeting after a parent makes an initial request, and 30 school days to develop an IEP after a student is determined to be eligible.',
    Link: 'https://undivided.io/resources/132',
  },
  {
    Word: 'training',
    Definition:
      'Did you know that one of the related services an IEP can provide is parent counseling and training?',
    Link: 'https://undivided.io/resources/131',
  },
  {
    Word: 'transition',
    Definition:
      'An Individual Transition Plan (ITP) is required as part of an IEP once a student turns 16. The transitions from preschool to kindergarten, from elementary to middle school, and from middle to high school are other big leaps.',
    Link: 'https://undivided.io/resources/476',
  },
  {
    Word: 'traumatic',
    Definition:
      'Traumatic: A brain injury that results from head trauma. Traumatic brain injury (TBI) adversely affects a child’s educational performance, and is one of thirteen categories in which a child may be eligible for special education.',
    Link: 'https://undivided.io/resources/129',
  },
  {
    Word: 'triennial',
    Definition:
      "Every three years, an IEP team must reassess the student's eligibility for special education. The process often involves extensive testing to establish eligibility, including standardized testing. This is often referred to as a triennial assessment or triennial IEP.",
    Link: 'https://undivided.io/resources/304',
  },
  {
    Word: 'tvi',
    Definition: 'Teacher of Students with Visual Impairments',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'undivided',
    Definition: 'We are unstoppable together!',
    Link: 'https://undivided.io/',
  },
  {
    Word: 'universal',
    Definition:
      '... means everything and everyone. Universal Design is an inclusive practice intended to include all individuals irrespective of their background or ability.',
    Link: 'https://undivided.io/resources/78',
  },
  {
    Word: 'wechsler',
    Definition:
      "The Wechsler Intelligence Scale for Children (WISC) is a test that measures a child's intellectual ability and 5 cognitive domains that impact performance, and is sometimes used as an assessment for an IEP or IEE.",
    Link: 'https://undivided.io/resources/115',
  },
  {
    Word: 'wisc',
    Definition:
      "Wechsler Intelligence Scale for Children is a test that measures a child's intellectual ability and 5 cognitive domains that impact performance, and is sometimes used as an assessment for an IEP or IEE.",
    Link: 'https://undivided.io/resources/115',
  },
]
